name: Build and Push Docker Image for request-headers

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  actions: write

env:
  FEATURE_BRANCH_BUMP_TYPE: patch
  MAIN_BRANCH_BUMP_TYPE: pre_l

# Normal patch versioning operational config reference:
#
#  FEATURE_BRANCH_BUMP_TYPE: patch
#  MAIN_BRANCH_BUMP_TYPE: pre_l

jobs:
  build-and-push:
    if: "!contains(github.actor, 'github-actions[bot]')"
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_HUB_IMAGE_NAME }}

    steps:
    - name: Check Out Code
      uses: actions/checkout@v4.2.2

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Set Up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.12

    - name: Cache Python Dependencies
      uses: actions/cache@v4.2.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install bump-my-version
      run: pip install bump-my-version

    - name: Determine Version Bump Type
      id: determine-bump
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "BUMP_TYPE=pre_l" >> $GITHUB_ENV
        else
          echo "BUMP_TYPE=pre_n" >> $GITHUB_ENV
        fi

    - name: Bump version
      id: bump
      uses: callowayproject/bump-my-version@master
      env:
        BUMPVERSION_TAG: "true"
      with:
        args: ${{ env.BUMP_TYPE }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Bumped Version
      id: get-bumped-version
      run: |
        echo "NEW_VERSION=$(bump-my-version show current_version)" >> $GITHUB_ENV

    - name: Debug New Version
      run: |
        echo "Version was bumped to ${{ env.NEW_VERSION }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker Image for Main Branch
      if: github.ref_name == 'main'
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:${{ env.NEW_VERSION }}
          ${{ env.DOCKER_IMAGE_NAME }}:latest
        platforms: linux/arm64,linux/amd64
        provenance: true
        sbom: true

    - name: Build and Push Docker Image for Non-Main Branches
      if: github.ref_name != 'main'
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:${{ env.NEW_VERSION }}
        platforms: linux/arm64,linux/amd64
        provenance: true
        sbom: true